a=[]
a.extend ([1,2,3,True,False,'hello','hallo'])
#print(a)
#a.append ([1,2,3, True,False,'hello','hallo'])
#print(a)
#a.append (1)
#a.append ('hello')
#a.append (True)
#print(a)
a.insert(2,'new')
print(a)
a.pop()
print(a)
del a[2]
print(a)
a.pop(2)
print(a)
a.clear ()
print(a)